services:
  - mysql

language: php
php:
  - 5.6
  - 7.0

before_script:
  - mysql -e 'create database hobbiz_test;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install --prefer-dist --dev
  - php bin/console doctrine:schema:update --dump-sql --force --env=test

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  slack: hobbiz:4OrqA0wjy4WJIfevRuBitodo
